testing module pipeline

diff --git a/.github/actions/templates/tfValidatePlan/action.yml b/.github/actions/templates/tfValidatePlan/action.yml
--- a/.github/actions/templates/tfValidatePlan/action.yml
+++ b/.github/actions/templates/tfValidatePlan/action.yml
@@ -26,144 +26,123 @@ inputs:
 runs:
   using: 'composite'
   steps:
-    timeout-minutes: 360
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ${{ inputs.modulePath }}
-    steps:
-    - name: Checkout the code
-      uses: actions/checkout@main
-  
-    # Log into Azure via OIDC
-    - uses: azure/login@v1
-      with:
-        client-id: ${{ secrets.AZURE_CLIENT_ID }}
-        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
+  - name: Terraform Init
+    id: init
+    run: |
+      terraform init \
+        -backend-config="resource_group_name=${{ secrets.AZURE_TF_STATE_RESOURCE_GROUP_NAME }}"   \
+        -backend-config="storage_account_name=${{ secrets.AZURE_TF_STATE_STORAGE_ACCOUNT_NAME }}" \
+        -backend-config="container_name=${{ secrets.AZURE_TF_STATE_STORAGE_CONTAINER_NAME }}"     \
+        -backend-config="key=${{ inputs.backend_key }}"
+    env:
+      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
+      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+      ARM_USE_OIDC: true
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
-      with:
-        terraform_version: ${{ inputs.terraform_version }}
+  - name: Terraform Validate
+    id: validate
+    run: terraform validate -no-color
 
-    - name: Terraform Init
-      id: init
-      run: |
-        terraform init \
-          -backend-config="resource_group_name=${{ secrets.AZURE_TF_STATE_RESOURCE_GROUP_NAME }}"   \
-          -backend-config="storage_account_name=${{ secrets.AZURE_TF_STATE_STORAGE_ACCOUNT_NAME }}" \
-          -backend-config="container_name=${{ secrets.AZURE_TF_STATE_STORAGE_CONTAINER_NAME }}"     \
-          -backend-config="key=${{ inputs.backend_key }}"
-      env:
-        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
-        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-        ARM_USE_OIDC: true
+  - name: tfsec
+    uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
+    with:
+      tfsec_args: --soft-fail
+      github_token: ${{ github.token }}
 
-    - name: Terraform Validate
-      id: validate
-      run: terraform validate -no-color
+  - name: Terraform Plan
+    id: plan
+    continue-on-error: true
+    run: |
+      if [ "${{ github.event.inputs.destroy }}" = "true" ]; then
+        terraform plan \
+          -destroy \
+          -input=false \
+          -out=tfplan \
+          -no-color \
+          -var-file="${{ inputs.tfvarPath }}"
+      else
+        terraform plan \
+          -input=false \
+          -out=tfplan \
+          -no-color \
+          -var-file="${{ inputs.tfvarPath }}"
+      fi
+    env:  
+      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
+      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+      ARM_USE_OIDC: true
 
-    - name: tfsec
-      uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
-      with:
-        tfsec_args: --soft-fail
-        github_token: ${{ github.token }}
+  - name: Show TFPlan
+    id: show
+    if: steps.plan.outcome == 'success'
+    run: terraform show -no-color tfplan
 
-    - name: Terraform Plan
-      id: plan
-      continue-on-error: true
-      run: |
-        if [ "${{ github.event.inputs.destroy }}" = "true" ]; then
-          terraform plan \
-            -destroy \
-            -input=false \
-            -out=tfplan \
-            -no-color \
-            -var-file="${{ inputs.tfvarPath }}"
-        else
-          terraform plan \
-            -input=false \
-            -out=tfplan \
-            -no-color \
-            -var-file="${{ inputs.tfvarPath }}"
-        fi
-      env:  
-        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
-        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-        ARM_USE_OIDC: true
+  - name: 'Upload TFPlan Artifact'
+    if: steps.plan.outcome == 'success'
+    uses: actions/upload-artifact@v3
+    with:
+      name: ${{ github.run_id }}.tfplan
+      path: ${{ inputs.modulePath }}/tfplan
+      retention-days: 5
 
-    - name: Show TFPlan
-      id: show
-      if: steps.plan.outcome == 'success'
-      run: terraform show -no-color tfplan
+  - name: Post Plan to GitHub PR
+    uses: actions/github-script@v6
+    if: github.event_name == 'pull_request' && steps.plan.outcome == 'success'
+    env:
+      PLAN: "terraform\n${{ steps.show.outputs.stdout }}"
+    with:
+      script: |
+        const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+        #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+        #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+        <details><summary>Validation Output</summary>
 
-    - name: 'Upload TFPlan Artifact'
-      if: steps.plan.outcome == 'success'
-      uses: actions/upload-artifact@v3
-      with:
-        name: ${{ github.run_id }}.tfplan
-        path: ${{ inputs.modulePath }}/tfplan
-        retention-days: 5
+        \`\`\`\n
+        ${{ steps.validate.outputs.stdout }}
+        \`\`\`
 
-    - name: Post Plan to GitHub PR
-      uses: actions/github-script@v6
-      if: github.event_name == 'pull_request' && steps.plan.outcome == 'success'
-      env:
-        PLAN: "terraform\n${{ steps.show.outputs.stdout }}"
-      with:
-        script: |
-          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-          <details><summary>Validation Output</summary>
+        </details>
 
-          \`\`\`\n
-          ${{ steps.validate.outputs.stdout }}
-          \`\`\`
+        #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
 
-          </details>
+        <details><summary>Show Plan</summary>
 
-          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+        \`\`\`\n
+        ${{ steps.show.outputs.stdout }}
+        \`\`\`
 
-          <details><summary>Show Plan</summary>
+        </details>
 
-          \`\`\`\n
-          ${{ steps.show.outputs.stdout }}
-          \`\`\`
+        *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.modulePath }}\`, Workflow: \`${{ github.workflow }}\`*`;
+        
+        await github.rest.issues.createComment({
+          issue_number: context.issue.number,
+          owner: context.repo.owner,
+          repo: context.repo.repo,
+          body: output
+        })
 
-          </details>
+  - name: Post Plan Failure
+    if: github.event_name == 'pull_request' && steps.plan.outcome == 'failure'
+    uses: actions/github-script@v6
+    with:
+      script: |
+        const output = `#### Terraform Plan failed
+        <details><summary>Plan Error Output</summary>
 
-          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.modulePath }}\`, Workflow: \`${{ github.workflow }}\`*`;
-          
-          await github.rest.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
+        \`\`\`\n
+        ${{ steps.plan.outputs.stderr }}
+        \`\`\`
 
-    - name: Post Plan Failure
-      if: github.event_name == 'pull_request' && steps.plan.outcome == 'failure'
-      uses: actions/github-script@v6
-      with:
-        script: |
-          const output = `#### Terraform Plan failed
-          <details><summary>Plan Error Output</summary>
-
-          \`\`\`\n
-          ${{ steps.plan.outputs.stderr }}
-          \`\`\`
-
-          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.modulePath }}\`, Workflow: \`${{ github.workflow }}\`*`;
-          await github.rest.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
-    - name: Exit if plan failed
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+        *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.modulePath }}\`, Workflow: \`${{ github.workflow }}\`*`;
+        await github.rest.issues.createComment({
+          issue_number: context.issue.number,
+          owner: context.repo.owner,
+          repo: context.repo.repo,
+          body: output
+        })
+  - name: Exit if plan failed
+    if: steps.plan.outcome == 'failure'
+    run: exit 1
